volumes:
  postgres_test_catalog_data:
  localstack_test_catalogue_data:

networks:
  catalogue-system-network:
    external: false

services:
  localstack-catalogue-test:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEFAULT_REGION=${DEFAULT_REGION-us-east-1}
      - SERVICES=${SERVICES-lambda,s3,apigateway,cloudwatch,dynamodb,sqs,kinesis,serverless,secretsmanager}
      - EDGE_PORT=4566
      - DATA_DIR=${DATA_DIR-./data}:/tmp/localstack
      - DEBUG=${DEBUG-}message_handler_service
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "localstack_test_catalogue_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - catalogue-system-network

  postgres-catalogue-test:
    image: postgres:16.0-alpine
    hostname: postgres-catalogue-test
    ports:
      - "5432:5432"
    env_file:
      - .env.test.template
    volumes:
      - postgres_test_catalog_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - catalogue-system-network

  catalogue-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app/
    command: python -m pytest -s -vv -x --cov --cov-report=html:/app/reports/coverage
    depends_on:
      - postgres-catalogue-test
    env_file:
      - .env.test.template
    networks:
      - catalogue-system-network
